apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: webapps
  labels:
    app: docker_image
  name: docker-image-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker_image
  strategy: {}
  template:
    metadata:
      labels:
        app: docker_image
    spec:
      containers:
      - image: gundala22reddy/docker_image:3
        name: docker-image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: webapps
  name: docker-image-service
spec:
  type: LoadBalancer
  selector:
    app: docker_image
  ports:
  - protocol: TCP
    port: 80       # The port that the service will expose
    targetPort: 80 # The port on the container that the service will forward traffic to
